import { NextRequest, NextResponse } from 'next/server'
import { api } from "@/convex/_generated/api"
import { convexHttp } from "@/lib/convex-server"

export async function POST(request: NextRequest, { params }: { params: { id: string } }) {
  try {
    const { paymentMethod, cardLast4, paymentPlan, sessionId } = await request.json()
    const paymentId = params.id

    // Get payment details
    const payment = await convexHttp.query(api.payments.getPayment as any, { id: paymentId as any })
    if (!payment) {
      return NextResponse.json({ error: 'Payment not found' }, { status: 404 })
    }

    // Normalize method token for storage
    const methodToken = (() => {
      const v = String(paymentMethod || '').toLowerCase()
      if (v === 'credit_card' || v === 'card' || v === 'stripe' || v === 'stripe_card') return 'stripe_card'
      if (v === 'check' || v === 'cheque') return 'check'
      if (v === 'cash') return 'cash'
      return 'stripe_card'
    })()

    // Mark paid and persist payment method so UI badges can display correctly
    await convexHttp.mutation(api.payments.updatePayment as any, {
      id: paymentId as any,
      status: 'paid',
      paidAt: Date.now(),
      paymentMethod: methodToken,
      notes: cardLast4 ? `Paid via ${methodToken} • **** ${cardLast4}` : undefined,
    } as any)

    // Payment history is automatically generated by the getPaymentHistory query

    return NextResponse.json({
      success: true,
      message: 'Payment completed successfully',
      paymentId: paymentId
    })

  } catch (error) {
    console.error('Error completing payment:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
} 