name: E2E - Playwright

on:
  pull_request:
    branches: [ main, develop, dev, staging ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest

    env:
      # Base URL for tests. Prefer secret if set; fallback to production.
      E2E_BASE_URL: ${{ secrets.E2E_BASE_URL || 'https://ra1dashboard.vercel.app' }}
      # Useful for Playwright HTML report retention
      PLAYWRIGHT_JUNIT_OUTPUT_NAME: junit.xml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests (list reporter)
        run: npx playwright test --reporter=list --config=playwright.config.ts

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore

      - name: Upload test results (videos, screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          if-no-files-found: ignore

